# Generated by Django 4.0.4 on 2022-05-01 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service', '0002_auto_20220501_1216'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locationCode', models.CharField(max_length=3)),
                ('locationName', models.CharField(max_length=200)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
    ]
